In [81]:
open_file = open('All Banks of Pakistan.csv', encoding = 'utf-8')
import csv
read_file = csv.reader(open_file)
Bank_list = list(read_file)

In [82]:
Bank_list

[['Bank Name',
  'Location (HQ)',
  'Category',
  'Total Capital (PKR Billion)',
  'Date of Establishment',
  'Owner Name / Major Shareholder'],
 ['National Bank of Pakistan (NBP)',
  'Karachi',
  'Government',
  '310.5',
  '1949-11-09',
  'Government of Pakistan'],
 ['Habib Bank Limited (HBL)',
  'Karachi',
  'Private',
  '360.2',
  '1941-08-25',
  'Aga Khan Fund for Economic Development'],
 ['United Bank Limited (UBL)',
  'Karachi',
  'Private',
  '316.2',
  '1959-11-07',
  'Bestway Group'],
 ['MCB Bank Limited',
  'Lahore',
  'Private',
  '255.8',
  '1947-07-09',
  'Nishat Group (Mian Mansha)'],
 ['Allied Bank Limited (ABL)',
  'Lahore',
  'Private',
  '233.9',
  '1942-12-03',
  'Ibrahim Group'],
 ['Meezan Bank Limited',
  'Karachi',
  'Private',
  '195.4',
  '2002-01-31',
  'Noor Financial Investment Co. (Kuwait)'],
 ['Bank Alfalah Limited',
  'Karachi',
  'Private',
  '145',
  '1997-06-21',
  'Abu Dhabi Group'],
 ['Bank Al Habib Limited',
  'Karachi',
  'Private',
  '132.5',
  '1991-10-15',
  'Habib Family'],
 ['Standard Chartered Bank',
  'Karachi',
  'Private',
  '115',
  '2006-05-19',
  'Standard Chartered PLC (UK)'],
 ['The Bank of Punjab (BOP)',
  'Lahore',
  'Government',
  '88.4',
  '1989-07-30',
  'Government of Punjab'],
 ['Faysal Bank Limited',
  'Karachi',
  'Private',
  '92.1',
  '1994-10-03',
  'Ithmaar Bank (Bahrain)'],
 ['Habib Metropolitan Bank',
  'Karachi',
  'Private',
  '86.7',
  '1992-10-16',
  'Habib Family (Habib Bank AG Zurich)'],
 ['Askari Bank Limited',
  'Rawalpindi',
  'Private',
  '78.2',
  '1991-10-09',
  'Fauji Foundation'],
 ['Bank of Khyber (BOK)',
  'Peshawar',
  'Government',
  '40.2',
  '1991-09-17',
  'Government of Khyber Pakhtunkhwa'],
 ['BankIslami Pakistan',
  'Karachi',
  'Private',
  '45.8',
  '2004-10-18',
  'JS Group'],
 ['JS Bank Limited', 'Karachi', 'Private', '42.5', '2006-03-15', 'JS Group'],
 ['Soneri Bank Limited',
  'Karachi',
  'Private',
  '38.2',
  '1991-09-28',
  'Feerasta Family']]

In [83]:
Bank_list[1]

['National Bank of Pakistan (NBP)',
 'Karachi',
 'Government',
 '310.5',
 '1949-11-09',
 'Government of Pakistan']

In [84]:
import pandas as pd

In [85]:
All_Banks = pd.read_csv('All Banks of Pakistan.csv' , encoding = 'latin-1')
All_Banks

,Bank Name,Location (HQ),Category,Total Capital (PKR Billion),Date of Establishment,Owner Name / Major Shareholder
0,National Bank of Pakistan (NBP),Karachi,Government,310.5,1949-11-09,Government of Pakistan
1,Habib Bank Limited (HBL),Karachi,Private,360.2,1941-08-25,Aga Khan Fund for Economic Development
2,United Bank Limited (UBL),Karachi,Private,316.2,1959-11-07,Bestway Group
3,MCB Bank Limited,Lahore,Private,255.8,1947-07-09,Nishat Group (Mian Mansha)
4,Allied Bank Limited (ABL),Lahore,Private,233.9,1942-12-03,Ibrahim Group
5,Meezan Bank Limited,Karachi,Private,195.4,2002-01-31,Noor Financial Investment Co. (Kuwait)
6,Bank Alfalah Limited,Karachi,Private,145.0,1997-06-21,Abu Dhabi Group
7,Bank Al Habib Limited,Karachi,Private,132.5,1991-10-15,Habib Family
8,Standard Chartered Bank,Karachi,Private,115.0,2006-05-19,Standard Chartered PLC (UK)
9,The Bank of Punjab (BOP),Lahore,Government,88.4,1989-07-30,Government of Punjab
10,Faysal Bank Limited,Karachi,Private,92.1,1994-10-03,Ithmaar Bank (Bahrain)
11,Habib Metropolitan Bank,Karachi,Private,86.7,1992-10-16,Habib Family (Habib Bank AG Zurich)
12,Askari Bank Limited,Rawalpindi,Private,78.2,1991-10-09,Fauji Foundation
13,Bank of Khyber (BOK),Peshawar,Government,40.2,1991-09-17,Government of Khyber Pakhtunkhwa
14,BankIslami Pakistan,Karachi,Private,45.8,2004-10-18,JS Group
15,JS Bank Limited,Karachi,Private,42.5,2006-03-15,JS Group
16,Soneri Bank Limited,Karachi,Private,38.2,1991-09-28,Feerasta Family

In [86]:
All_Banks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Bank Name                       17 non-null     object
 1   Location (HQ)                   17 non-null     object
 2   Category                        17 non-null     object
 3   Total Capital (PKR Billion)     17 non-null     float64
 4   Date of Establishment           17 non-null     object
 5   Owner Name / Major Shareholder  17 non-null     object
dtypes: float64(1), object(5)
memory usage: 948.0+ bytes

In [87]:
All_Banks.describe()

       Total Capital (PKR Billion)
count                    17.000000
mean                    151.564706
std                     106.844993
min                      38.200000
25%                      78.200000
50%                     115.000000
75%                     233.900000
max                     360.200000

In [88]:
All_Banks.shape

(17, 6)

In [89]:
All_Banks.head()

,Bank Name,Location (HQ),Category,Total Capital (PKR Billion),Date of Establishment,Owner Name / Major Shareholder
0,National Bank of Pakistan (NBP),Karachi,Government,310.5,1949-11-09,Government of Pakistan
1,Habib Bank Limited (HBL),Karachi,Private,360.2,1941-08-25,Aga Khan Fund for Economic Development
2,United Bank Limited (UBL),Karachi,Private,316.2,1959-11-07,Bestway Group
3,MCB Bank Limited,Lahore,Private,255.8,1947-07-09,Nishat Group (Mian Mansha)
4,Allied Bank Limited (ABL),Lahore,Private,233.9,1942-12-03,Ibrahim Group

In [90]:
All_Banks.isnull().sum()

Bank Name                         0
Location (HQ)                     0
Category                          0
Total Capital (PKR Billion)       0
Date of Establishment             0
Owner Name / Major Shareholder    0
dtype: int64

In [91]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [92]:
ABOP = All_Banks
ABOP

,Bank Name,Location (HQ),Category,Total Capital (PKR Billion),Date of Establishment,Owner Name / Major Shareholder
0,National Bank of Pakistan (NBP),Karachi,Government,310.5,1949-11-09,Government of Pakistan
1,Habib Bank Limited (HBL),Karachi,Private,360.2,1941-08-25,Aga Khan Fund for Economic Development
2,United Bank Limited (UBL),Karachi,Private,316.2,1959-11-07,Bestway Group
3,MCB Bank Limited,Lahore,Private,255.8,1947-07-09,Nishat Group (Mian Mansha)
4,Allied Bank Limited (ABL),Lahore,Private,233.9,1942-12-03,Ibrahim Group
5,Meezan Bank Limited,Karachi,Private,195.4,2002-01-31,Noor Financial Investment Co. (Kuwait)
6,Bank Alfalah Limited,Karachi,Private,145.0,1997-06-21,Abu Dhabi Group
7,Bank Al Habib Limited,Karachi,Private,132.5,1991-10-15,Habib Family
8,Standard Chartered Bank,Karachi,Private,115.0,2006-05-19,Standard Chartered PLC (UK)
9,The Bank of Punjab (BOP),Lahore,Government,88.4,1989-07-30,Government of Punjab
10,Faysal Bank Limited,Karachi,Private,92.1,1994-10-03,Ithmaar Bank (Bahrain)
11,Habib Metropolitan Bank,Karachi,Private,86.7,1992-10-16,Habib Family (Habib Bank AG Zurich)
12,Askari Bank Limited,Rawalpindi,Private,78.2,1991-10-09,Fauji Foundation
13,Bank of Khyber (BOK),Peshawar,Government,40.2,1991-09-17,Government of Khyber Pakhtunkhwa
14,BankIslami Pakistan,Karachi,Private,45.8,2004-10-18,JS Group
15,JS Bank Limited,Karachi,Private,42.5,2006-03-15,JS Group
16,Soneri Bank Limited,Karachi,Private,38.2,1991-09-28,Feerasta Family

In [93]:
Details_of_Banks = pd.read_csv('Monthly Capital of Top Banks.csv' , encoding = 'latin-1' )
Details_of_Banks.head()

,Bank Name,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec (Est)
0,HBL,365,368,371.9,385,410,444.1,450,455,464.0,470,478,482.5
1,NBP,310,312,315.2,318,322,328.0,329,330,332.1,335,338,341.0
2,UBL,316,318,321.0*,325,330,335.2,337,338,340.2,342,345,348.2
3,MCB Bank,255,258,262.1,265,270,275.4,277,278,280.6,283,286,289.5
4,Allied Bank,232,235,238.5,240,242,245.2,247,249,251.4,254,257,260.4

In [94]:
Details_of_Banks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Bank Name  11 non-null     object
 1   Jan        11 non-null     int64
 2   Feb        11 non-null     int64
 3   Mar        11 non-null     object
 4   Apr        11 non-null     int64
 5   May        11 non-null     int64
 6   Jun        11 non-null     float64
 7   Jul        11 non-null     int64
 8   Aug        11 non-null     int64
 9   Sep        11 non-null     float64
 10  Oct        11 non-null     int64
 11  Nov        11 non-null     int64
 12  Dec (Est)  11 non-null     float64
dtypes: float64(3), int64(8), object(2)
memory usage: 1.2+ KB

In [95]:
Details_of_Banks.describe()

,Jan,Feb,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec (Est)
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
mean,206.363636,208.545455,214.727273,219.363636,225.872727,227.818182,229.636364,232.845455,235.636364,239.000000,242.618182
std,96.778379,97.310188,100.663887,105.768873,112.608730,113.673056,114.447606,115.870905,116.939534,118.502321,118.936620
min,87.000000,88.000000,90.000000,91.000000,92.500000,93.000000,94.000000,95.800000,97.000000,98.000000,99.800000
25%,123.500000,125.000000,128.000000,129.000000,131.150000,132.500000,133.500000,135.500000,137.000000,139.000000,142.350000
50%,195.000000,198.000000,208.000000,212.000000,218.400000,222.000000,226.000000,232.000000,238.000000,245.000000,251.200000
75%,282.500000,285.000000,291.500000,296.000000,301.700000,303.000000,304.000000,306.350000,309.000000,312.000000,315.250000
max,365.000000,368.000000,385.000000,410.000000,444.100000,450.000000,455.000000,464.000000,470.000000,478.000000,482.500000

In [96]:
month_columns = Details_of_Banks.columns[1:] # Jan through Dec

def clean_data(value):
    if isinstance(value, str):
        # Keep only numbers and decimal points
        value = ''.join(c for c in value if c.isdigit() or c == '.')
    return float(value)

In [97]:
for col in month_columns:
    Details_of_Banks[col] = Details_of_Banks[col].apply(clean_data)

In [98]:
X = np.array(range(1, 13)).reshape(-1, 1) 
X_future = np.array(range(13, 16)).reshape(-1, 1)

predictions_list = []

In [99]:
# STEP 4: Train and Predict for each bank
for index, row in Details_of_Banks.iterrows():
    bank_name = row['Bank Name']
    y = row[month_columns].values # The 12 months of capital
    
    # Initialize the model
    model = LinearRegression()
    
    # "Fit" the model (This is the actual Machine Learning part)
    model.fit(X, y)
    
    # Predict the future
    future_capital = model.predict(X_future)
    
    # Store the results
    predictions_list.append({
        'Bank': bank_name,
        'Janauray 26': round(future_capital[0], 2),
        'Febuary 26': round(future_capital[1], 2),
        'March 26': round(future_capital[2], 2),
        'Trend_Strength (R2)': round(model.score(X, y), 3)
    })

In [100]:
# STEP 5: View Results
results_df = pd.DataFrame(predictions_list)
print(results_df)

# Save it to a new file
results_df.to_csv('my_bank_predictions.csv', index=False)

           Bank  Janauray 26  Febuary 26  March 26  Trend_Strength (R2)
0           HBL       508.29      520.54    532.80                0.938
1           NBP       344.25      347.08    349.91                0.983
2           UBL       352.19      355.15    358.11                0.974
3      MCB Bank       293.33      296.41    299.50                0.980
4   Allied Bank       261.84      264.28    266.72                0.995
5        Meezan       253.85      258.97    264.09                0.993
6       Alfalah       203.28      205.88    208.49                0.992
7      Al Habib       158.75      161.14    163.52                0.991
8     SCB (Pak)       125.91      126.72    127.54                0.967
9        Faysal       108.92      110.47    112.02                0.985
10          BOP       100.30      101.44    102.57                0.993